#!/bin/bash
  echo Input Desired KML Filename
	read FILENAME
	sudo python /home/pi/products/kml_files/netxml2kml.py --kml -o $FILENAME /home/pi/products/kismet_files/*.netxml /home/pi/products/kml_files
