#! /bin/sh
# /etc/init.d/tightvncserver
#
### BEGIN INIT INFO
# Provides:          tightvncserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Sign in when ready..."
 /usr/bin/tightvncserver
    ;;
  stop)
    killall/or_stop tightvncserver
    echo "Connection Closed"
    ;;
  *)
    echo "Usage: /etc/init.d/tightvncserver {start|stop}"
    exit 1
    ;;
esac

exit 0
